### PR TITLE
Update challenge002.md

### PR DESCRIPTION
**Pull request by everuner**
Add contributions for Challenge 002

### CODE REVIEW

**Comment by jimmy3dita** [comment]
This guide is not anymore actual: please update the staking pool creation with the call to the `stakehouse.betanet` contract.

The rest looks very good, and is accepted :)

**Comment by everuner** [comment]
> pdate the staking pool creation with the call to the `stakehouse.betanet` contrac

Just updated and add info about pool creation with the call to the stakehouse.betanet contract

**Comment by jimmy3dita** [comment]
I still can't see on the [Medium article](https://medium.com/@serj_czech/%D0%BF%D1%83%D0%BB-%D1%81%D1%82%D0%B0%D0%B2%D0%BE%D0%BA-%D0%B4%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81-%D1%81%D0%B1%D0%BE%D1%80-%D0%BA%D0%BE%D0%BC%D0%B8%D1%81%D1%81%D0%B8%D0%B8-stake-wars-challenge-002-19c172b3d0) the explanation on how to deploy the staking pool using the pool factory:

**Comment by everuner** [comment]
> I still can't see on the [Medium article](https://medium.com/@serj_czech/%D0%BF%D1%83%D0%BB-%D1%81%D1%82%D0%B0%D0%B2%D0%BE%D0%BA-%D0%B4%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81-%D1%81%D0%B1%D0%BE%D1%80-%D0%BA%D0%BE%D0%BC%D0%B8%D1%81%D1%81%D0%B8%D0%B8-stake-wars-challenge-002-19c172b3d0) the explanation on how to deploy the staking pool using the pool factory:

Made changes, please check, thx

**Pull request merged**
